#spring:
#  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: create
#      dialect: org.hibernate.dialect.PostgreSQLDialect

#spring:
#  datasource:
#    url: jdbc:postgresql://postgres:DZTODgKcgrmIgsTofHgXnxuehWvLTMyS@tramway.proxy.rlwy.net:52978/railway
#    username: postgres
#    password: DZTODgKcgrmIgsTofHgXnxuehWvLTMyS
#  jpa:
#    open-in-view: false
#    hibernate:
#        ddl-auto: create
#        dialect: org.hibernate.dialect.PostgreSQLDialect

spring:
  datasource:
#    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    url: jdbc:mysql://root:fIZeGetXeVdQPXUOmkMsPMZoOMERhsKy@metro.proxy.rlwy.net:16753/railway
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL8Dialect

no build.gradle:
  tasks.jar{
  manifest{
  attributes["Main-Class"] = "DIO.api.bancaria20.Application"
  criar Procfile?
  web: java -jar